schema_template = {
    "cars_data": "cars",
    "car_names": "cars",
    "model_list": "model",
    "car_makers": "car makers",
    "countries": "countries",
    "continents": "continents",

    "cars_data.*": "every item",
    "cars_data.id": "id",
    "cars_data.MPG": "Miles Per Gallon",
    "cars_data.Cylinders": "cylinders",
    "cars_data.Edispl": "edispl",
    "cars_data.Horsepower": "horsepower",
    "cars_data.Weight": "weight",
    "cars_data.Accelerate": "speed",
    "cars_data.Year": "manufacture year",
    "car_names.*": "every item",
    "car_names.MakeId": "id",
    "car_names.Model": "model",
    "car_names.Make": "make",
    "model_list.*": "every item",
    "model_list.ModelId": "id",
    "model_list.Maker": "maker id",
    "model_list.Model": "name",
    "car_makers.*": "every item",
    "car_makers.Id": "id",
    "car_makers.Maker": "name",
    "car_makers.FullName": "full name",
    "car_makers.Country": "country",
    "countries.*": "every item",
    "countries.CountryId": "id",
    "countries.CountryName": "name",
    "countries.continent": "continent",
    "continents.*": "every item",
    "continents.ContId": "id",
    "continents.Continent": "name"
}
