schema_template = {
    "concert": "concert",
    "singer": "singer",
    "singer_in_concert": "singer performed in concert",
    "stadium": "stadium",

    "singer.Singer_ID": "id",
    "singer.Name": "name",
    "singer.Country": "country",
    "singer.Song_Name": "song",
    "singer.Song_release_year": "song release year",
    "singer.Age": "age",
    "singer.Is_male": "is male",
    "concert.concert_ID": "id",
    "concert.concert_Name": "name",
    "concert.Theme": "theme",
    "concert.Stadium_ID": "stadium id",
    "concert.Year": "year",
    "singer_in_concert.concert_ID": "concert id",
    "singer_in_concert.Singer_ID": "singer id",
    "stadium.Stadium_ID": "id",
    "stadium.Location": "location",
    "stadium.Name": "name",
    "stadium.Capacity": "capacity",
    "stadium.Highest": "highest audience record",
    "stadium.Lowest": "lowest audience record",
    "stadium.Average": "average audience record"
}
