from sys import modules
from raser.geometry import R3dDetector
from raser.pyfenics import FenicsCal
from raser.g4particles import Particles
from raser.calcurrent import CalCurrentG4P
from raser.calcurrent import CalCurrentLaser
from raser.elereadout import Amplifier
from raser.setting import Setting
from raser.model import Material
from raser.model import Avalanche
from raser.source import TCTTracks
from raser.g4beam_monitor import Beammonitor
from raser.g4reactor import reactor