
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-22T17:12:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d230724d3ea7f672984cb0e9ca48b08799c511ed",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
