# coding: utf-8

"""
    Splitit.OnBoarding.Api.V2

    Splitit's Onboarding API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from splitit_client import schemas  # noqa: F401


class CreateMerchantResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by Konfig.
    Ref: https://konfigthis.com

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "merchantStatus",
            "merchantTempId",
        }
        
        class properties:
            merchantTempId = schemas.StrSchema
            merchantStatus = schemas.StrSchema
            __annotations__ = {
                "merchantTempId": merchantTempId,
                "merchantStatus": merchantStatus,
            }
    
    merchantStatus: MetaOapg.properties.merchantStatus
    merchantTempId: MetaOapg.properties.merchantTempId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantTempId"]) -> MetaOapg.properties.merchantTempId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchantStatus"]) -> MetaOapg.properties.merchantStatus: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["merchantTempId", "merchantStatus", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantTempId"]) -> MetaOapg.properties.merchantTempId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchantStatus"]) -> MetaOapg.properties.merchantStatus: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["merchantTempId", "merchantStatus", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        merchantStatus: typing.Union[MetaOapg.properties.merchantStatus, str, ],
        merchantTempId: typing.Union[MetaOapg.properties.merchantTempId, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CreateMerchantResponse':
        return super().__new__(
            cls,
            *args,
            merchantStatus=merchantStatus,
            merchantTempId=merchantTempId,
            _configuration=_configuration,
            **kwargs,
        )
