# coding: utf-8

"""
    https://api.partner.microsoft.com/v1.0/ingestion

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ListingImageApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def products_product_id_listings_listing_id_images_get(self, product_id, listing_id, authorization, **kwargs):  # noqa: E501
        """Returns a paged collection of ListingImage resources  # noqa: E501

        Sample request:                    GET /products/{productID}/listings/{listingID}/images                      returns all ListingImage resources for a given listing                      # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_get(product_id, listing_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param str authorization: User authorization (required)
        :param str expand: Use $expand=FileSasUri to Include SAS URI in response
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsListingsListingImage_
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_listings_listing_id_images_get_with_http_info(product_id, listing_id, authorization, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_listings_listing_id_images_get_with_http_info(product_id, listing_id, authorization, **kwargs)  # noqa: E501
            return data

    def products_product_id_listings_listing_id_images_get_with_http_info(self, product_id, listing_id, authorization, **kwargs):  # noqa: E501
        """Returns a paged collection of ListingImage resources  # noqa: E501

        Sample request:                    GET /products/{productID}/listings/{listingID}/images                      returns all ListingImage resources for a given listing                      # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_get_with_http_info(product_id, listing_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param str authorization: User authorization (required)
        :param str expand: Use $expand=FileSasUri to Include SAS URI in response
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsListingsListingImage_
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['product_id', 'listing_id', 'authorization', 'expand', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_listings_listing_id_images_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_listings_listing_id_images_get`")  # noqa: E501
        # verify the required parameter 'listing_id' is set
        if ('listing_id' not in params or
                params['listing_id'] is None):
            raise ValueError("Missing the required parameter `listing_id` when calling `products_product_id_listings_listing_id_images_get`")  # noqa: E501
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_listings_listing_id_images_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501
        if 'listing_id' in params:
            path_params['listingID'] = params['listing_id']  # noqa: E501

        query_params = []
        if 'expand' in params:
            query_params.append(('$expand', params['expand']))  # noqa: E501

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/listings/{listingID}/images', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsListingsListingImage_',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def products_product_id_listings_listing_id_images_image_id_delete(self, product_id, listing_id, image_id, authorization, **kwargs):  # noqa: E501
        """Deletes a ListingImage resource  # noqa: E501

        Sample request:                    DELETE /products/{productID}/listings/{listingID}/images/{imageID}  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_image_id_delete(product_id, listing_id, image_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param str image_id: ID of image (required)
        :param str authorization: User authorization (required)
        :param str client_request_id: ID of request provIDed by user
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_listings_listing_id_images_image_id_delete_with_http_info(product_id, listing_id, image_id, authorization, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_listings_listing_id_images_image_id_delete_with_http_info(product_id, listing_id, image_id, authorization, **kwargs)  # noqa: E501
            return data

    def products_product_id_listings_listing_id_images_image_id_delete_with_http_info(self, product_id, listing_id, image_id, authorization, **kwargs):  # noqa: E501
        """Deletes a ListingImage resource  # noqa: E501

        Sample request:                    DELETE /products/{productID}/listings/{listingID}/images/{imageID}  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_image_id_delete_with_http_info(product_id, listing_id, image_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param str image_id: ID of image (required)
        :param str authorization: User authorization (required)
        :param str client_request_id: ID of request provIDed by user
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['product_id', 'listing_id', 'image_id', 'authorization', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_listings_listing_id_images_image_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_listings_listing_id_images_image_id_delete`")  # noqa: E501
        # verify the required parameter 'listing_id' is set
        if ('listing_id' not in params or
                params['listing_id'] is None):
            raise ValueError("Missing the required parameter `listing_id` when calling `products_product_id_listings_listing_id_images_image_id_delete`")  # noqa: E501
        # verify the required parameter 'image_id' is set
        if ('image_id' not in params or
                params['image_id'] is None):
            raise ValueError("Missing the required parameter `image_id` when calling `products_product_id_listings_listing_id_images_image_id_delete`")  # noqa: E501
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_listings_listing_id_images_image_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501
        if 'listing_id' in params:
            path_params['listingID'] = params['listing_id']  # noqa: E501
        if 'image_id' in params:
            path_params['imageID'] = params['image_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/listings/{listingID}/images/{imageID}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def products_product_id_listings_listing_id_images_image_id_get(self, product_id, listing_id, image_id, authorization, **kwargs):  # noqa: E501
        """Returns a ListingImage resource  # noqa: E501

        Sample request:                    GET /products/{productID}/listings/{listingID}/images/{imageID}  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_image_id_get(product_id, listing_id, image_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param str image_id: ID of image (required)
        :param str authorization: User authorization (required)
        :param str expand: Use $expand=FileSasUri to Include SAS URI in response
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsListingsListingImage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_listings_listing_id_images_image_id_get_with_http_info(product_id, listing_id, image_id, authorization, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_listings_listing_id_images_image_id_get_with_http_info(product_id, listing_id, image_id, authorization, **kwargs)  # noqa: E501
            return data

    def products_product_id_listings_listing_id_images_image_id_get_with_http_info(self, product_id, listing_id, image_id, authorization, **kwargs):  # noqa: E501
        """Returns a ListingImage resource  # noqa: E501

        Sample request:                    GET /products/{productID}/listings/{listingID}/images/{imageID}  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_image_id_get_with_http_info(product_id, listing_id, image_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param str image_id: ID of image (required)
        :param str authorization: User authorization (required)
        :param str expand: Use $expand=FileSasUri to Include SAS URI in response
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsListingsListingImage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['product_id', 'listing_id', 'image_id', 'authorization', 'expand', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_listings_listing_id_images_image_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_listings_listing_id_images_image_id_get`")  # noqa: E501
        # verify the required parameter 'listing_id' is set
        if ('listing_id' not in params or
                params['listing_id'] is None):
            raise ValueError("Missing the required parameter `listing_id` when calling `products_product_id_listings_listing_id_images_image_id_get`")  # noqa: E501
        # verify the required parameter 'image_id' is set
        if ('image_id' not in params or
                params['image_id'] is None):
            raise ValueError("Missing the required parameter `image_id` when calling `products_product_id_listings_listing_id_images_image_id_get`")  # noqa: E501
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_listings_listing_id_images_image_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501
        if 'listing_id' in params:
            path_params['listingID'] = params['listing_id']  # noqa: E501
        if 'image_id' in params:
            path_params['imageID'] = params['image_id']  # noqa: E501

        query_params = []
        if 'expand' in params:
            query_params.append(('$expand', params['expand']))  # noqa: E501

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/listings/{listingID}/images/{imageID}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsListingsListingImage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def products_product_id_listings_listing_id_images_image_id_put(self, authorization, if_match, product_id, listing_id, image_id, **kwargs):  # noqa: E501
        """Updates a ListingImage resource  # noqa: E501

        Sample request:                    PUT /products/{productID}/listings/{listingID}/images/{imageID} [Body ListingImage]  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_image_id_put(authorization, if_match, product_id, listing_id, image_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: User authorization (required)
        :param str if_match: ETag of the resource to be matched (required)
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param str image_id: ID of image (required)
        :param MicrosoftIngestionApiModelsListingsListingImage body: Request body of a Microsoft.Ingestion.Api.Models.Listings.ListingImage
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsListingsListingImage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_listings_listing_id_images_image_id_put_with_http_info(authorization, if_match, product_id, listing_id, image_id, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_listings_listing_id_images_image_id_put_with_http_info(authorization, if_match, product_id, listing_id, image_id, **kwargs)  # noqa: E501
            return data

    def products_product_id_listings_listing_id_images_image_id_put_with_http_info(self, authorization, if_match, product_id, listing_id, image_id, **kwargs):  # noqa: E501
        """Updates a ListingImage resource  # noqa: E501

        Sample request:                    PUT /products/{productID}/listings/{listingID}/images/{imageID} [Body ListingImage]  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_image_id_put_with_http_info(authorization, if_match, product_id, listing_id, image_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: User authorization (required)
        :param str if_match: ETag of the resource to be matched (required)
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param str image_id: ID of image (required)
        :param MicrosoftIngestionApiModelsListingsListingImage body: Request body of a Microsoft.Ingestion.Api.Models.Listings.ListingImage
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsListingsListingImage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'if_match', 'product_id', 'listing_id', 'image_id', 'body', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_listings_listing_id_images_image_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_listings_listing_id_images_image_id_put`")  # noqa: E501
        # verify the required parameter 'if_match' is set
        if ('if_match' not in params or
                params['if_match'] is None):
            raise ValueError("Missing the required parameter `if_match` when calling `products_product_id_listings_listing_id_images_image_id_put`")  # noqa: E501
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_listings_listing_id_images_image_id_put`")  # noqa: E501
        # verify the required parameter 'listing_id' is set
        if ('listing_id' not in params or
                params['listing_id'] is None):
            raise ValueError("Missing the required parameter `listing_id` when calling `products_product_id_listings_listing_id_images_image_id_put`")  # noqa: E501
        # verify the required parameter 'image_id' is set
        if ('image_id' not in params or
                params['image_id'] is None):
            raise ValueError("Missing the required parameter `image_id` when calling `products_product_id_listings_listing_id_images_image_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501
        if 'listing_id' in params:
            path_params['listingID'] = params['listing_id']  # noqa: E501
        if 'image_id' in params:
            path_params['imageID'] = params['image_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501
        if 'if_match' in params:
            header_params['If-Match'] = params['if_match']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/listings/{listingID}/images/{imageID}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsListingsListingImage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def products_product_id_listings_listing_id_images_post(self, authorization, product_id, listing_id, **kwargs):  # noqa: E501
        """Creates a ListingImage resource  # noqa: E501

        Sample request:                    POST /products/{productID}/listings/{listingID}/images [Body ListingImage]  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_post(authorization, product_id, listing_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: User authorization (required)
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param MicrosoftIngestionApiModelsListingsListingImage body: Request body of a Microsoft.Ingestion.Api.Models.Listings.ListingImage
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsListingsListingImage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_listings_listing_id_images_post_with_http_info(authorization, product_id, listing_id, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_listings_listing_id_images_post_with_http_info(authorization, product_id, listing_id, **kwargs)  # noqa: E501
            return data

    def products_product_id_listings_listing_id_images_post_with_http_info(self, authorization, product_id, listing_id, **kwargs):  # noqa: E501
        """Creates a ListingImage resource  # noqa: E501

        Sample request:                    POST /products/{productID}/listings/{listingID}/images [Body ListingImage]  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_listings_listing_id_images_post_with_http_info(authorization, product_id, listing_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: User authorization (required)
        :param str product_id: ID of product (required)
        :param str listing_id: ID of listing (required)
        :param MicrosoftIngestionApiModelsListingsListingImage body: Request body of a Microsoft.Ingestion.Api.Models.Listings.ListingImage
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsListingsListingImage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'product_id', 'listing_id', 'body', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_listings_listing_id_images_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_listings_listing_id_images_post`")  # noqa: E501
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_listings_listing_id_images_post`")  # noqa: E501
        # verify the required parameter 'listing_id' is set
        if ('listing_id' not in params or
                params['listing_id'] is None):
            raise ValueError("Missing the required parameter `listing_id` when calling `products_product_id_listings_listing_id_images_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501
        if 'listing_id' in params:
            path_params['listingID'] = params['listing_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/listings/{listingID}/images', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsListingsListingImage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
