
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-21T11:05:42+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "23021d69e665dadc66e56a40667e296f6304fd9a",
 "version": "1.51.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
