from distance import euclidean_distance
from loads import loadData
from numpy_transformations import mcol, mrow
from preprocessing import oneHotEncoding
from visualization import histogram_attributeVSfrequency, scatter_attributeVSattribute