# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\blite\2023_poo2\MapaNovo\pasta_ui\tela_conversor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_conversor(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 590)
        MainWindow.setStyleSheet("background-color: rgb(101, 255, 111);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(155, 10, 329, 37))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(60, 60, 60);\n"
"border-radius:15px;\n"
"")
        self.label.setObjectName("label")
        self.lineEdit_endere_E = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_endere_E.setGeometry(QtCore.QRect(110, 110, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_endere_E.setFont(font)
        self.lineEdit_endere_E.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_endere_E.setText("")
        self.lineEdit_endere_E.setObjectName("lineEdit_endere_E")
        self.pushButton_conv_End = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_conv_End.setGeometry(QtCore.QRect(250, 180, 99, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_conv_End.setFont(font)
        self.pushButton_conv_End.setStyleSheet("")
        self.pushButton_conv_End.setObjectName("pushButton_conv_End")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar.setGeometry(QtCore.QRect(500, 530, 84, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.label_lon_B = QtWidgets.QLabel(self.centralwidget)
        self.label_lon_B.setGeometry(QtCore.QRect(31, 119, 70, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_lon_B.setFont(font)
        self.label_lon_B.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_lon_B.setObjectName("label_lon_B")
        self.label_lat_B = QtWidgets.QLabel(self.centralwidget)
        self.label_lat_B.setGeometry(QtCore.QRect(70, 490, 70, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_lat_B.setFont(font)
        self.label_lat_B.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_lat_B.setObjectName("label_lat_B")
        self.label_lat = QtWidgets.QLabel(self.centralwidget)
        self.label_lat.setGeometry(QtCore.QRect(70, 370, 44, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_lat.setFont(font)
        self.label_lat.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_lat.setObjectName("label_lat")
        self.lineEdit_lat_C = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lat_C.setGeometry(QtCore.QRect(120, 370, 113, 20))
        self.lineEdit_lat_C.setStyleSheet("    background-color: rgb(230, 230, 230);\n"
"    border: 2px solid rgb(160,160, 160);\n"
"    border-radius: 5px;\n"
"\n"
"")
        self.lineEdit_lat_C.setText("")
        self.lineEdit_lat_C.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_lat_C.setDragEnabled(False)
        self.lineEdit_lat_C.setReadOnly(False)
        self.lineEdit_lat_C.setObjectName("lineEdit_lat_C")
        self.lineEdit_lon_C = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lon_C.setGeometry(QtCore.QRect(120, 400, 113, 20))
        self.lineEdit_lon_C.setStyleSheet("    background-color: rgb(230, 230, 230);\n"
"    border: 2px solid rgb(160, 160, 160);\n"
"    border-radius: 5px;\n"
"\n"
"")
        self.lineEdit_lon_C.setObjectName("lineEdit_lon_C")
        self.label_lon = QtWidgets.QLabel(self.centralwidget)
        self.label_lon.setGeometry(QtCore.QRect(60, 400, 57, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_lon.setFont(font)
        self.label_lon.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_lon.setObjectName("label_lon")
        self.label_resul_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_resul_4.setGeometry(QtCore.QRect(204, 332, 194, 24))
        self.label_resul_4.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resul_4.setFont(font)
        self.label_resul_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color:rgb(35, 255, 53)")
        self.label_resul_4.setObjectName("label_resul_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 320, 602, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_resul_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_resul_5.setGeometry(QtCore.QRect(220, 70, 194, 21))
        self.label_resul_5.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resul_5.setFont(font)
        self.label_resul_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(35, 255, 53)")
        self.label_resul_5.setObjectName("label_resul_5")
        self.label_lat_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_lat_2.setGeometry(QtCore.QRect(50, 240, 44, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_lat_2.setFont(font)
        self.label_lat_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_lat_2.setObjectName("label_lat_2")
        self.label_lon_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_lon_2.setGeometry(QtCore.QRect(40, 272, 57, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_lon_2.setFont(font)
        self.label_lon_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"")
        self.label_lon_2.setObjectName("label_lon_2")
        self.pushButton_conv_Coord = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_conv_Coord.setGeometry(QtCore.QRect(250, 430, 99, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_conv_Coord.setFont(font)
        self.pushButton_conv_Coord.setStyleSheet("")
        self.pushButton_conv_Coord.setObjectName("pushButton_conv_Coord")
        self.lineEdit_lat_E = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lat_E.setGeometry(QtCore.QRect(100, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_lat_E.setFont(font)
        self.lineEdit_lat_E.setStyleSheet("    background-color: rgb(230, 230, 230);\n"
"    border: 2px solid rgb(219, 236, 255);\n"
"    border-radius: 5px;\n"
"\n"
"")
        self.lineEdit_lat_E.setText("")
        self.lineEdit_lat_E.setPlaceholderText("")
        self.lineEdit_lat_E.setObjectName("lineEdit_lat_E")
        self.lineEdit_lon_E = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lon_E.setGeometry(QtCore.QRect(100, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_lon_E.setFont(font)
        self.lineEdit_lon_E.setStyleSheet("    background-color: rgb(230, 230, 230);\n"
"    border: 2px solid rgb(219, 236, 255);\n"
"    border-radius: 5px;\n"
"\n"
"")
        self.lineEdit_lon_E.setText("")
        self.lineEdit_lon_E.setPlaceholderText("")
        self.lineEdit_lon_E.setObjectName("lineEdit_lon_E")
        self.lineEdit_enderc_Coord = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_enderc_Coord.setGeometry(QtCore.QRect(145, 490, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_enderc_Coord.setFont(font)
        self.lineEdit_enderc_Coord.setStyleSheet("    background-color: rgb(230, 230, 230);\n"
"    border: 2px solid rgb(219, 236, 255);\n"
"    border-radius: 5px;\n"
"\n"
"")
        self.lineEdit_enderc_Coord.setText("")
        self.lineEdit_enderc_Coord.setPlaceholderText("")
        self.lineEdit_enderc_Coord.setObjectName("lineEdit_enderc_Coord")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#ffffff;\">Conversor de Coordenadas</span></p><p><br/></p></body></html>"))
        self.lineEdit_endere_E.setPlaceholderText(_translate("MainWindow", "     ex: São Paulo, Brasil"))
        self.pushButton_conv_End.setText(_translate("MainWindow", "Converter"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))
        self.label_lon_B.setText(_translate("MainWindow", "<html><head/><body><p>Endereço</p></body></html>"))
        self.label_lat_B.setText(_translate("MainWindow", "<html><head/><body><p>Endereço</p></body></html>"))
        self.label_lat.setText(_translate("MainWindow", "Latitude"))
        self.lineEdit_lat_C.setPlaceholderText(_translate("MainWindow", "ex: -7.0823544"))
        self.lineEdit_lon_C.setPlaceholderText(_translate("MainWindow", "ex: -41.4685053"))
        self.label_lon.setText(_translate("MainWindow", "Longitude"))
        self.label_resul_4.setText(_translate("MainWindow", "<html><head/><body><p>Coordenadas em Endereço</p></body></html>"))
        self.label_resul_5.setText(_translate("MainWindow", "<html><head/><body><p>Endereço em Coordenadas</p><p><br/></p></body></html>"))
        self.label_lat_2.setText(_translate("MainWindow", "Latitude"))
        self.label_lon_2.setText(_translate("MainWindow", "Longitude"))
        self.pushButton_conv_Coord.setText(_translate("MainWindow", "Converter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_conversor()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
