# coding: utf-8

"""
    https://api.partner.microsoft.com/v1.0/ingestion

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PropertyApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def products_product_id_properties_get(self, product_id, authorization, **kwargs):  # noqa: E501
        """Returns a paged collection of Property resources for a Product  # noqa: E501

        Sample request:                    GET /products/{productID}/properties  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_get(product_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str authorization: User authorization (required)
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsPropertiesBaseProperty_
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_properties_get_with_http_info(product_id, authorization, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_properties_get_with_http_info(product_id, authorization, **kwargs)  # noqa: E501
            return data

    def products_product_id_properties_get_with_http_info(self, product_id, authorization, **kwargs):  # noqa: E501
        """Returns a paged collection of Property resources for a Product  # noqa: E501

        Sample request:                    GET /products/{productID}/properties  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_get_with_http_info(product_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str authorization: User authorization (required)
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsPropertiesBaseProperty_
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['product_id', 'authorization', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_properties_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_properties_get`")  # noqa: E501
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_properties_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/properties', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsPropertiesBaseProperty_',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get(self, product_id, instance_id, authorization, **kwargs):  # noqa: E501
        """Returns a paged collection of Property resources for a Product  # noqa: E501

        Sample request:                   GET /products/{productID}/properties/getByInstanceID(instanceID={instanceID})  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get(product_id, instance_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str instance_id: Resource instance ID (required)
        :param str authorization: User authorization (required)
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsPropertiesBaseProperty_
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get_with_http_info(product_id, instance_id, authorization, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get_with_http_info(product_id, instance_id, authorization, **kwargs)  # noqa: E501
            return data

    def products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get_with_http_info(self, product_id, instance_id, authorization, **kwargs):  # noqa: E501
        """Returns a paged collection of Property resources for a Product  # noqa: E501

        Sample request:                   GET /products/{productID}/properties/getByInstanceID(instanceID={instanceID})  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get_with_http_info(product_id, instance_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str instance_id: Resource instance ID (required)
        :param str authorization: User authorization (required)
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsPropertiesBaseProperty_
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['product_id', 'instance_id', 'authorization', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get`")  # noqa: E501
        # verify the required parameter 'instance_id' is set
        if ('instance_id' not in params or
                params['instance_id'] is None):
            raise ValueError("Missing the required parameter `instance_id` when calling `products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get`")  # noqa: E501
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_properties_get_by_instance_id_instance_i_dinstance_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501
        if 'instance_id' in params:
            path_params['instanceID'] = params['instance_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/properties/getByInstanceID(instanceID={instanceID})', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsCommonPagedCollectionMicrosoftIngestionApiModelsPropertiesBaseProperty_',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def products_product_id_properties_post(self, authorization, product_id, **kwargs):  # noqa: E501
        """Create a Property resource for a Product  # noqa: E501

        Sample request:                    POST /products/{productID}/properties [Body Property]  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_post(authorization, product_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: User authorization (required)
        :param str product_id: ID of product (required)
        :param MicrosoftIngestionApiModelsPropertiesAzureProperty body: Request body of a Microsoft.Ingestion.Api.Models.Properties.BaseProperty
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsPropertiesAzureProperty
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_properties_post_with_http_info(authorization, product_id, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_properties_post_with_http_info(authorization, product_id, **kwargs)  # noqa: E501
            return data

    def products_product_id_properties_post_with_http_info(self, authorization, product_id, **kwargs):  # noqa: E501
        """Create a Property resource for a Product  # noqa: E501

        Sample request:                    POST /products/{productID}/properties [Body Property]  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_post_with_http_info(authorization, product_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: User authorization (required)
        :param str product_id: ID of product (required)
        :param MicrosoftIngestionApiModelsPropertiesAzureProperty body: Request body of a Microsoft.Ingestion.Api.Models.Properties.BaseProperty
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsPropertiesAzureProperty
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'product_id', 'body', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_properties_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_properties_post`")  # noqa: E501
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_properties_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/properties', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsPropertiesAzureProperty',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def products_product_id_properties_property_id_get(self, product_id, property_id, authorization, **kwargs):  # noqa: E501
        """Returns a Property resource for a Product  # noqa: E501

        Sample request:                    GET /products/{productID}/properties/{propertyID}  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_property_id_get(product_id, property_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str property_id: ID of Property (required)
        :param str authorization: User authorization (required)
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsPropertiesAzureProperty
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_properties_property_id_get_with_http_info(product_id, property_id, authorization, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_properties_property_id_get_with_http_info(product_id, property_id, authorization, **kwargs)  # noqa: E501
            return data

    def products_product_id_properties_property_id_get_with_http_info(self, product_id, property_id, authorization, **kwargs):  # noqa: E501
        """Returns a Property resource for a Product  # noqa: E501

        Sample request:                    GET /products/{productID}/properties/{propertyID}  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_property_id_get_with_http_info(product_id, property_id, authorization, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str product_id: ID of product (required)
        :param str property_id: ID of Property (required)
        :param str authorization: User authorization (required)
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsPropertiesAzureProperty
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['product_id', 'property_id', 'authorization', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_properties_property_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_properties_property_id_get`")  # noqa: E501
        # verify the required parameter 'property_id' is set
        if ('property_id' not in params or
                params['property_id'] is None):
            raise ValueError("Missing the required parameter `property_id` when calling `products_product_id_properties_property_id_get`")  # noqa: E501
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_properties_property_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501
        if 'property_id' in params:
            path_params['propertyID'] = params['property_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/properties/{propertyID}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsPropertiesAzureProperty',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def products_product_id_properties_property_id_put(self, authorization, if_match, product_id, property_id, **kwargs):  # noqa: E501
        """Update the Property resource for a Product  # noqa: E501

        Sample request:                    PUT /products/{productID}/properties/{propertyID} [Body Property]  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_property_id_put(authorization, if_match, product_id, property_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: User authorization (required)
        :param str if_match: ETag of the resource to be matched (required)
        :param str product_id: ID of product (required)
        :param str property_id: ID of Property (required)
        :param MicrosoftIngestionApiModelsPropertiesAzureProperty body: Request body of a Microsoft.Ingestion.Api.Models.Properties.BaseProperty
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsPropertiesAzureProperty
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.products_product_id_properties_property_id_put_with_http_info(authorization, if_match, product_id, property_id, **kwargs)  # noqa: E501
        else:
            (data) = self.products_product_id_properties_property_id_put_with_http_info(authorization, if_match, product_id, property_id, **kwargs)  # noqa: E501
            return data

    def products_product_id_properties_property_id_put_with_http_info(self, authorization, if_match, product_id, property_id, **kwargs):  # noqa: E501
        """Update the Property resource for a Product  # noqa: E501

        Sample request:                    PUT /products/{productID}/properties/{propertyID} [Body Property]  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.products_product_id_properties_property_id_put_with_http_info(authorization, if_match, product_id, property_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str authorization: User authorization (required)
        :param str if_match: ETag of the resource to be matched (required)
        :param str product_id: ID of product (required)
        :param str property_id: ID of Property (required)
        :param MicrosoftIngestionApiModelsPropertiesAzureProperty body: Request body of a Microsoft.Ingestion.Api.Models.Properties.BaseProperty
        :param str client_request_id: ID of request provIDed by user
        :return: MicrosoftIngestionApiModelsPropertiesAzureProperty
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['authorization', 'if_match', 'product_id', 'property_id', 'body', 'client_request_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method products_product_id_properties_property_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'authorization' is set
        if ('authorization' not in params or
                params['authorization'] is None):
            raise ValueError("Missing the required parameter `authorization` when calling `products_product_id_properties_property_id_put`")  # noqa: E501
        # verify the required parameter 'if_match' is set
        if ('if_match' not in params or
                params['if_match'] is None):
            raise ValueError("Missing the required parameter `if_match` when calling `products_product_id_properties_property_id_put`")  # noqa: E501
        # verify the required parameter 'product_id' is set
        if ('product_id' not in params or
                params['product_id'] is None):
            raise ValueError("Missing the required parameter `product_id` when calling `products_product_id_properties_property_id_put`")  # noqa: E501
        # verify the required parameter 'property_id' is set
        if ('property_id' not in params or
                params['property_id'] is None):
            raise ValueError("Missing the required parameter `property_id` when calling `products_product_id_properties_property_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'product_id' in params:
            path_params['productID'] = params['product_id']  # noqa: E501
        if 'property_id' in params:
            path_params['propertyID'] = params['property_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'authorization' in params:
            header_params['Authorization'] = params['authorization']  # noqa: E501
        if 'client_request_id' in params:
            header_params['Client-Request-ID'] = params['client_request_id']  # noqa: E501
        if 'if_match' in params:
            header_params['If-Match'] = params['if_match']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/products/{productID}/properties/{propertyID}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MicrosoftIngestionApiModelsPropertiesAzureProperty',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
