# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deep/proto/common/v1/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!deep/proto/common/v1/common.proto\x12\x14\x64\x65\x65p.proto.common.v1\"\xbb\x01\n\x10TracePointConfig\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0f\n\x07line_no\x18\x03 \x01(\x05\x12>\n\x04\x61rgs\x18\x04 \x03(\x0b\x32\x30.deep.proto.common.v1.TracePointConfig.ArgsEntry\x12\x0f\n\x07watches\x18\x05 \x03(\t\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42i\n\"com.intergral.deep.proto.common.v1B\x0b\x43ommonProtoP\x01Z4github.com/intergral/deep-proto/proto/deep/common/v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deep.proto.common.v1.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.intergral.deep.proto.common.v1B\013CommonProtoP\001Z4github.com/intergral/deep-proto/proto/deep/common/v1'
  _TRACEPOINTCONFIG_ARGSENTRY._options = None
  _TRACEPOINTCONFIG_ARGSENTRY._serialized_options = b'8\001'
  _TRACEPOINTCONFIG._serialized_start=60
  _TRACEPOINTCONFIG._serialized_end=247
  _TRACEPOINTCONFIG_ARGSENTRY._serialized_start=204
  _TRACEPOINTCONFIG_ARGSENTRY._serialized_end=247
# @@protoc_insertion_point(module_scope)
