
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-18T12:43:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8611526567b14c61aa3d9b13506bfd6aed6e789",
 "version": "3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
