# This file is autogenerated, don't edit it manually

__version__ = "1.67.4b430.post12185248.dev8"
__scala_version__ = "1.67.4-430-12185248-8-SNAPSHOT"
__spark_version__ = "1.67.1b430.post12185248.dev8"
