# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev59+ge2f5dcc.d20230322'
__version_tuple__ = version_tuple = (0, 1, 'dev59', 'ge2f5dcc.d20230322')
