VERSION_YEAR = 2023
VERSION_MONTH = int('03')
VERSION_DAY = int('21')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('25')
MAJOR_VERSION = 1
MINOR_VERSION = 2
PATCH_VERSION = 202303210725
version_date = '2023/03/21 07:25'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
