from dlt.types.bool import DltPayloadArgumentBoolType
from .sint import DltPayloadArgumentSIntType
from .uint import DltPayloadArgumentUIntType
from .floa import DltPayloadArgumentFloaType
from .aray import DltPayloadArgumentArayType
from .strg import DltPayloadArgumentStrgType
from .rawd import DltPayloadArgumentRawdType
from .trai import DltPayloadArgumentTraiType
from .stru import DltPayloadArgumentStruType
