from politicsnlp.form_of_government.regime import *
from politicsnlp.form_of_government.aristocracy import *
from politicsnlp.form_of_government.form_of_government import *
from politicsnlp.form_of_government.socialism import *
from politicsnlp.form_of_government.colonialism import *
from politicsnlp.form_of_government.communism import *
from politicsnlp.form_of_government.direct_democracy import *
from politicsnlp.form_of_government.representative_democracy import *
from politicsnlp.form_of_government.oligarchy import *
from politicsnlp.form_of_government.autocracy import *
from politicsnlp.form_of_government.monarchy import *
from politicsnlp.form_of_government.theocracy import *
