# coding: utf-8

"""
    Splitit.OnBoarding.Api.V2

    Splitit's Onboarding API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import splitit_client
from splitit_client.model.status_legend_response import StatusLegendResponse
from splitit_client import configuration


class TestStatusLegendResponse(unittest.TestCase):
    """StatusLegendResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
