from politicsnlp.people.person import *
from politicsnlp.people.masses import *
from politicsnlp.people.people import *
from politicsnlp.people.crowd import *
from politicsnlp.people.pink_youth import *
from politicsnlp.people.red_generation import *
from politicsnlp.people.political_elites import *
from politicsnlp.people.refugee import *
from politicsnlp.people.political_community import *
from politicsnlp.people.nationalist import *
from politicsnlp.people.populist import *