
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-20T15:11:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d49e6a0297d55d6bbf832a746ecd85fd766d11aa",
 "version": "1.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
