
from enum import Enum
class PrinterStatus(Enum): 
  OPEN_SERIAL = "OPEN_SERIAL"
  CONNECTING = "CONNECTING"
  OPERATIONAL = "OPERATIONAL"
  PRINTING = "PRINTING"
  PAUSED = "PAUSED"
  CLOSED = "CLOSED"
  ERROR = "ERROR"
  UNKNOWN = "UNKNOWN"
  CLOSED_WITH_ERROR = "CLOSED_WITH_ERROR"