from politicsnlp.principle.justice import *
from politicsnlp.principle.freedom import *
from politicsnlp.principle.democracy import *
from politicsnlp.principle.spirit_of_the_law import *
from politicsnlp.principle.separation_of_powers import *
from politicsnlp.principle.natural_rights import *
from politicsnlp.principle.freedom_of_speech import *
from politicsnlp.principle.popular_sovereignty import *
from politicsnlp.principle.harm_principle import *
