
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-20T08:56:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa88aec5173e58622f6c0b1ba4e46f9e881ebb58",
 "version": "0.1.0a86"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
