
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-20T10:49:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1b15fbd4d5233ebd43fcefe1a1c6a949116d18e",
 "version": "2.1.2.post0.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
